[tools]
awscli = "latest"
checkov = "latest"
deno = "latest"
golang = "latest"
helm = "latest"
infracost = "latest"
k9s = "latest"
node = "latest"
pipx = "latest"
python = "latest"
ruby = "latest"
rust = "latest"
terraform = "latest"
terraform-docs = "latest"
terrascan = "latest"
tflint = "latest"
tfupdate = "latest"
trivy = "latest"
"npm:wrangler" = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-core" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform", "ruby"]
